apiVersion: apps/v1            # API para recursos de tipo Deployment
kind: Deployment               # Tipo de recurso: Deployment
metadata:
  name: secret-test-deployment # Nombre del Deployment
spec:
  replicas: 1                  # Solo 1 réplica para el laboratorio
  selector:
    matchLabels:
      app: secret-test         # Label que identifica a los Pods del Deployment
  template:
    metadata:
      labels:
        app: secret-test       # Label aplicado a los Pods
    spec:
      containers:
        - name: test-container             # Nombre del contenedor
          image: busybox                  # Imagen ligera para pruebas
          command: ["/bin/sh", "-c", "env && sleep 3600"]
                                            # Imprime variables de entorno
                                            # y se queda vivo 1 hora
          envFrom:
            - secretRef:
                name: mysecret             # Carga TODAS las keys del Secret
                                            # como variables de entorno
