apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "ls /host && sleep 3600"]
    volumeMounts:
    - name: host-volume        # Nombre del volumen
      mountPath: /host         # Ruta dentro del contenedor
  volumes:
  - name: host-volume
    hostPath:                 # Usa filesystem del nodo
      path: /tmp              # Ruta REAL en el worker
      type: Directory         # Verifica que exista