apiVersion: v1
kind: PersistentVolume           # Recurso de almacenamiento real
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 2Gi                # Capacidad disponible
  accessModes:
    - ReadWriteOnce             # Un nodo a la vez
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/pv-data          # Backend físico (solo para labs)