apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo-k8s
data:
  APP_MESSAGE: "Hola desde ConfigMap (GitOps + Argo CD)"
  APP_ENV: demo
  LOG_LEVEL: debug
  app.properties: |
    feature.enabled=true
    ui.color=blue