apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: {{ .Values.namespace }}
data:
  APP_MESSAGE: "{{ .Values.config.appMessage }}"
  APP_ENV: "{{ .Values.config.appEnv }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  app.properties: |
{{ .Values.config.appProperties | indent 4 }}
