apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: {{ .Values.cronjob.image | quote }}
              imagePullPolicy: {{ .Values.cronjob.imagePullPolicy }}
              command:
{{ toYaml .Values.cronjob.command | indent 16 }}
          restartPolicy: OnFailure
