apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: demo-app-sa
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: APP_MESSAGE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: demo-app-config
        - name: secret-volume
          secret:
            secretName: demo-app-secret
