apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.secret.dbUser }}"
  DB_PASSWORD: "{{ .Values.secret.dbPassword }}"
