apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"name":"save-me"},"name":"save-me","namespace":"find-me"},"spec":{"containers":[{"args":["sleep infinity"],"command":["sh","-c"],"image":"alpine","name":"myapp","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2026-05-15T20:32:05Z"
  generation: 1
  labels:
    name: save-me
  name: save-me
  namespace: find-me
  resourceVersion: "55157"
  uid: 0d6671f6-6a54-413a-b1d9-0b779049b17b
spec:
  containers:
  - args:
    - sleep infinity
    command:
    - sh
    - -c
    image: alpine
    imagePullPolicy: Always
    name: myapp
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4pn4k
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: desktop-lph4g7g
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-4pn4k
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-05-15T20:32:08Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-05-15T20:32:05Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-05-15T20:32:08Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-05-15T20:32:08Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-05-15T20:32:05Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c0dee3696888f5fcb5c7854d016ef404bb7a758c6db2c8cfe6a17b051663508c
    image: docker.io/library/alpine:latest
    imageID: docker.io/library/alpine@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
    lastState: {}
    name: myapp
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-05-15T20:32:07Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4pn4k
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.18.240.147
  hostIPs:
  - ip: 172.18.240.147
  observedGeneration: 1
  phase: Running
  podIP: 10.42.0.194
  podIPs:
  - ip: 10.42.0.194
  qosClass: BestEffort
  startTime: "2026-05-15T20:32:05Z"
