apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: trouble
  labels:
    name: web
spec:
  containers:
  - name: web
    image: nginx:1.19-alpine
    ports:
    - containerPort: 80
  restartPolicy: Always
