version: '3.8' # Especifica la versión del formato de Docker Compose

services: # Define los contenedores que forman parte de tu aplicación
  jenkins: # Nombre del servicio dentro del stack
    image: jenkins/jenkins:lts # Imagen oficial de Jenkins con soporte a largo plazo
    container_name: jenkins-server # Nombre fijo para el contenedor (fácil de identificar en docker ps)
    restart: always # Reinicia el contenedor automáticamente si falla o si reinicias Linux Mint
    
    ports: # Mapeo de puertos: "Puerto_Host:Puerto_Contenedor"
      - "8080:8080"   # Puerto para acceder a la interfaz web (navegador)
      - "50000:50000" # Puerto usado para conectar nodos o agentes esclavos de Jenkins
    
    volumes: # Configuración de persistencia de datos
      - jenkins_home:/var/jenkins_home # Monta el volumen lógico en la carpeta de datos de Jenkins
    
    environment: # Variables de entorno para configurar el sistema interno
      - TZ=America/Bogota # Configura la zona horaria (ajústala según tu ubicación)
      - JAVA_OPTS=-Xmx1024m # (Opcional) Limita la memoria RAM que usará Java para no saturar tu PC

volumes: # Definición de los volúmenes globales
  jenkins_home: # Crea el volumen 'jenkins_home' si no existe
    driver: local # Usa el driver local de Docker para gestionar el almacenamiento en tu disco
